<?php

/**
 * @file
 * Provides hook implementations for Field Layout.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\field_layout\Form\FieldLayoutEntityFormDisplayEditForm;
use Drupal\field_layout\Form\FieldLayoutEntityViewDisplayEditForm;

/**
 * Implements hook_help().
 */
function field_layout_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.field_layout':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Field Layout module allows you to arrange fields into regions on forms and displays of entities such as nodes and users.') . '</p>';
      $output .= '<p>' . t('For more information, see the <a href=":field-layout-documentation">online documentation for the Field Layout module</a>.', [':field-layout-documentation' => 'https://www.drupal.org/documentation/modules/field_layout']) . '</p>';
      return $output;
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function field_layout_entity_type_alter(array &$entity_types) {
  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  // The form classes are only needed when Field UI is installed.
  if (\Drupal::moduleHandler()->moduleExists('field_ui')) {
    $entity_types['entity_view_display']->setFormClass('edit', FieldLayoutEntityViewDisplayEditForm::class);
    $entity_types['entity_form_display']->setFormClass('edit', FieldLayoutEntityFormDisplayEditForm::class);
  }
}
